directory: ~/media/music/
threaded: yes

plugins:
  - scrub

import:
  run: yes
  write: yes
  copy: no
  move: yes
  autotag: yes
  exclude: art

paths:
  default: $albumartist/$album/$track $title

scrub:
  auto: yes
