directory: ~/media/music/
threaded: yes

plugins:
  - scrub
  - embedart

import:
  run: yes
  write: yes
  copy: no
  move: yes
  autotag: yes
  languages: en

paths:
  default: $albumartist/$album/$track $title

scrub:
  auto: yes

embedart:
  quality: 75
