add_newline = false
continuation_prompt = '➜➜ '

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
\n$character"""

[fill]
symbol = ' '

[character]
success_symbol = '[➜](bold purple)'
error_symbol = '[➜](bold red)'
vicmd_symbol = '[➜](white)'

[directory]
truncation_length = 6
truncate_to_repo = false
style = 'bold blue'

[git_branch]
format = '[$branch]($style) '
style = 'bold yellow'

[git_status]
modified = '*'
format = '[${modified}${ahead_behind}]($style)'
style = 'bold yellow'

[cmd_duration]
min_time = 5000
format = '[$duration]($style)'
style = 'yellow'
