add_newline = false

format = """
$directory\
$git_branch\
$git_status\
\n$character"""

[character]
success_symbol = "[➜](bold purple)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[➜](white)"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "bold blue"

[git_branch]
format = "[$branch]($style) "
style = 'bold yellow'

[git_status]
modified = '*'
format = '[$modified]($style)'
style = 'bold yellow'
